---
  - hosts: all
    become: yes
    tasks:
    - name: install ppa
      shell: add-apt-repository ppa:openjdk-r/ppa

    - name: apt update
      shell: apt-get update -y

    - name: install open jdk
      shell: apt-get install -y openjdk-8-jdk

    - name: install mysql driver
      shell: apt-get install libmysql-java

    - name: configure mysql driver
      shell: export CLASSPATH=$CLASSPATH:/usr/share/java/mysql-connector-java.jar


