---
# tasks file for nginx
- name: Install Nginx
  yum: 
    name=nginx 
    state=present 
    update_cache=yes
#  action: >
#    {{ ansible_pkg_mgr }} name=nginx state=present update_cache=yes
  become: yes

#- name: write the Nginx config file
#  template: src=~/ansible-rails/roles/nginx/nginx_default dest=/etc/nginx/sites-available/default  
#  become: yes
#  notify:
#  - restart Nginx
- name: ensure Nginx is running (and enable it at boot)
  service: name=nginx state=started enabled=yes
  become: yes
